// <auto-generated />
using System;
using HiveLog.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HiveLog.Api.Migrations
{
    [DbContext(typeof(HiveLogDbContext))]
    [Migration("20260505192026_AddCallerToLogEntries")]
    partial class AddCallerToLogEntries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HiveLog.Api.Features.Logs.Models.LogEntry", b =>
                {
                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Caller")
                        .HasColumnType("text")
                        .HasColumnName("caller");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Exception")
                        .HasColumnType("jsonb")
                        .HasColumnName("exception");

                    b.Property<string>("InstanceId")
                        .HasColumnType("text")
                        .HasColumnName("instance_id");

                    b.Property<bool>("IsAuthenticated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_authenticated");

                    b.Property<short>("Level")
                        .HasColumnType("smallint")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("MessageTemplate")
                        .HasColumnType("text")
                        .HasColumnName("message_template");

                    b.Property<string>("ParentSpanId")
                        .HasColumnType("text")
                        .HasColumnName("parent_span_id");

                    b.Property<string>("Properties")
                        .HasColumnType("jsonb")
                        .HasColumnName("properties");

                    b.Property<string>("RequestId")
                        .HasColumnType("text")
                        .HasColumnName("request_id");

                    b.Property<string>("SessionId")
                        .HasColumnType("text")
                        .HasColumnName("session_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_type");

                    b.Property<string>("SpanId")
                        .HasColumnType("text")
                        .HasColumnName("span_id");

                    b.Property<string>("Stream")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("app")
                        .HasColumnName("stream");

                    b.PrimitiveCollection<string[]>("Tags")
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("TraceId")
                        .HasColumnType("text")
                        .HasColumnName("trace_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Timestamp", "Id")
                        .HasName("pk_log_entries");

                    b.HasIndex("Caller")
                        .HasDatabaseName("ix_log_entries_caller");

                    b.HasIndex("TraceId", "ParentSpanId")
                        .HasDatabaseName("ix_log_entries_trace_id_parent_span_id");

                    b.ToTable("log_entries", (string)null);
                });

            modelBuilder.Entity("HiveLog.Api.Features.Rules.Models.WebhookRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ActionBodyTemplate")
                        .HasColumnType("text")
                        .HasColumnName("action_body_template");

                    b.Property<string>("ActionUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action_url");

                    b.Property<int>("FireCountInWindow")
                        .HasColumnType("integer")
                        .HasColumnName("fire_count_in_window");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastFiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_fired_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("ThrottleMaxFires")
                        .HasColumnType("integer")
                        .HasColumnName("throttle_max_fires");

                    b.Property<int>("ThrottleWindowSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("throttle_window_seconds");

                    b.Property<short?>("TriggerLevelMin")
                        .HasColumnType("smallint")
                        .HasColumnName("trigger_level_min");

                    b.Property<string>("TriggerSource")
                        .HasColumnType("text")
                        .HasColumnName("trigger_source");

                    b.Property<string>("TriggerStream")
                        .HasColumnType("text")
                        .HasColumnName("trigger_stream");

                    b.PrimitiveCollection<string[]>("TriggerTags")
                        .HasColumnType("text[]")
                        .HasColumnName("trigger_tags");

                    b.Property<DateTimeOffset?>("WindowStartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_start_at");

                    b.HasKey("Id")
                        .HasName("pk_webhook_rules");

                    b.ToTable("webhook_rules", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
